[package]
name = "yam"
version = "0.1.0"
edition = "2024"

[dependencies]
edit = "0.1.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.141", features = ["preserve_order"] }
serde_yaml = "0.9.34"
tempfile = "3.20.0"
